import Head from 'next/head'

const Home = ({ foo, bar }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <div>
          Home page - {foo} - {bar}
        </div>
      </main>
    </>
  )
}

export async function getStaticProps() {
  const { foo, bar } = process.env;
  return {
    props: {
      foo, bar
    },
  };
}

export default Home;