import { Button } from '@mui/material';
import Head from 'next/head';
import { useEffect } from 'react';

const Home = () => {
  useEffect(() => {
    const sessionValidity = new Date(localStorage.getItem('session-validity'));
    if (sessionValidity < new Date()) {
      fetch('/api/createSession')
        .then((res) => res.json())
        .then((json) => {
          if (json.session !== '') {
            localStorage.setItem('session', json.session);
            localStorage.setItem('session-validity', json.expirationDate);
          }
        });
    }
  }, []);

  const fetchGods = async () => {
    const json = await fetch(
      `/api/gods?session=${localStorage.getItem('session')}`
    );
    console.log(json);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <div>Home page</div>
        <Button onClick={fetchGods}>Log gods</Button>
      </main>
    </>
  );
};

export default Home;
